### ISSUE TITLE
White flash when returning to attract screen does not reach sides

### ISSUE THREAD

**Issue by BenBergman** [winnitron/WinnitronLauncher#106]
When the screen flashes white to return to the attract screen, the white flash does not reach all the way to the left and right.

![img_20181023_192501](https://user-images.githubusercontent.com/142754/47434069-66236880-d767-11e8-90df-d62348bbf00c.jpg)

**Comment by aaronklaassen** [comment]
@mrmwiebe You're probably more qualified for this one than I am.

**Comment by BenBergman** [comment]
This happens at 1080p too.

**Comment by mrmwiebe** [comment]
On it.  Figured out how to do responsive UI design a bit and going to be working on a new branch that should hopefully fix issues at any resolution. :)

**Comment by mrmwiebe** [comment]
Fixed in latest pull-request.  Should be available with next release.
