### ISSUE TITLE
Winnitron launcher stuck at small size on large screens

### ISSUE THREAD

**Issue by BenBergman** [winnitron/WinnitronLauncher#108]
When connecting my Winnitron to a 2560x1440 monitor, the Winnitron launcher starts off full screen. Launching games goes to a full screen game. When I return from a game, the Winnitron launcher only fills the top left area of the screen (probably about 1080p worth). Using a resolution smaller than 1080p does not cause the Winnitron launcher to return to a size that is too big, so there is likely some sort of upper limit that is being hit here rather than a constant.

**Comment by mrmwiebe** [comment]
I'll take a look!

**Comment by mrmwiebe** [comment]
Fixed in latest pull-request.  Should be available with next release.
