### ISSUE TITLE
Some .ogg files cause launcher to get stuck at "compiling games"

### ISSUE THREAD

**Issue by BenBergman** [winnitron/WinnitronLauncher#109]
I tried replacing the default music with a custom track. I started with a `.wav` file which I soon realized isn't supported by the launcher. I did `ffmpeg -i track.wav track.ogg` to get an `ogg` file. Opening the launcher with this file caused it to hang at "compiling games".

[test_audio.zip](https://github.com/winnitron/WinnitronLauncher/files/2510743/test_audio.zip)

**Comment by mrmwiebe** [comment]
Ok did some digging and there's two things going on here:

One is that we coded in a very specific way of getting the track name and author using the format "Artist - Song", I can make that more tolerant like maybe just displaying the filename outright in the top right corner of the launcher, but you should be naming your tracks so it looks nice in the launcher regardless.  I'll make sure that's better communicated in the wiki.  This string parsing is actually what was freezing at "compiling games".  OOPS.  😅 

Second, I think there's something wonky with your encoder.  FMOD in Unity really doesn't like that OGG file from FFMPEG (straight up rejected the file), but if I convert the WAV you provided into an OGG using VLC Player it plays fine.

Thanks for sending those files!  Super helpful! 😄

**Comment by mrmwiebe** [comment]
Made it so the jukebox just displays the filename as is in top right menu bar so it should no longer hang on "compiling games".

**Comment by BenBergman** [comment]
Thanks for digging into this. I should have known better than to throw a random file name at a jukebox app that tries to nicely display names. I'll also try a different OGG converter.

Does FMOD support WAV files? Those might be more consistent in format for folks needing to do conversions.
