### ISSUE TITLE
Can't remove games from playlist

### ISSUE THREAD

**Issue by BenBergman** [winnitron/WinnitronLauncher#111]
I dug around for a bit but couldn't find a way to remove games from a playlist.

**Comment by mrmwiebe** [comment]
Are you using the Winnitron Network to sync your playlists?  If you are, and you're saying that you want to download a playlist but selectively remove games, I'm not sure that functionality exists, you'll need to create your own custom playlist.

If you're just adding games manually on your machine, you should be able to just delete the folder from the hard drive and the launcher should update it that way.  Make sure you don't do this with a Network synced folder though, that could probably cause issues.

**Comment by mrmwiebe** [comment]
You're right!  Can't find it either.  This is def a bug for @aaronklaassen, but since this is on the website, this is a Winnitron Network bug, not a Launcher bug.  Please open a new ticket here: https://github.com/winnitron/winnitron_reborn/issues
