### ISSUE TITLE
Several games won't launch due to wrong metadata

### ISSUE THREAD

**Issue by Ludonaut** [winnitron/WinnitronLauncher#17]
Most games currently on the network won't launch due to a wrong "executable" string in their respective winnitron_metadata.json files.

For example, Canabalt has the following

`{"title":"Canabalt", "slug":"canabalt", "last_modified":"2017-01-25T20:57:59", "min_players":"1", "max_players":"2", "executable":"null", "legacy_controls":"true", "image_url":"https://winnitron.s3-us-west-2.amazonaws.com/games/55f3a09d-6a55-4c55-86b4-9dbd03e8460b-image-Canabalt.png"}`

where it should be `"executable":"Canabalt.exe"`

4Forths and Binary System have a similar issues ("4Forths" instead of "4fourths.exe", and a missing dash with Binary System).

Skimming the code and output_log.txt, I noticed the launcher writing to the winnitron_metadata.json files, but I can't tell if it even touches the executable object, so this might not be an issue with the launcher but with the games.

**Comment by aaronklaassen** [comment]
Ah yeah some of that data was backfilled automatically. That's probably the problem. I'll go in and fix them.

**Comment by mrmwiebe** [comment]
I think this is the last bug before we can launch RC1. :)  Let me know if you've got it or if you want me to take a look.

**Comment by aaronklaassen** [comment]
@mrmwiebe No I got it. I fixed some of them but haven't finished yet. I'll do it today.

**Comment by mrmwiebe** [comment]
Fixed for RC1
