### ISSUE TITLE
Launcher should hide prefixed underscore of local-only playlists

### ISSUE THREAD

**Issue by Ludonaut** [winnitron/WinnitronLauncher#18]
So it took me a while to figure out how to stop the launcher from deleting my local folders, haha!

I gather the canonical way to keep local folders is to prefix them with an underscore:

`_My Super Exclusive Playlist`

But the underscore then shows up in the playlist name in the launcher as well! :sob: 

(also this should be mentioned on [the wiki page](https://github.com/winnitron/WinnitronLauncher/wiki/Managing-Your-Games) somewhere)

**Comment by aaronklaassen** [comment]
Yep I'm in the middle of updating a bunch of the docs. :+1: Didn't know about the `_` in-launcher though. @mrmwiebe wanna tackle that?

**Comment by mrmwiebe** [comment]
On it.

**Comment by mrmwiebe** [comment]
Fixed in commit b46bbb4484adfb40fb0836d1bec357ad1a94c333
