### ISSUE TITLE
White trails shouldn't clip through cover images

### ISSUE THREAD

**Issue by Ludonaut** [winnitron/WinnitronLauncher#20]
Okay this is a super low priority cosmetic issue and I'm not even sure if it should be changed really, but I feel like the white trails shouldn't clip through the cover images. It just feels weird.

This could probably be solved through some clever masking, but I have no idea where to begin. (sorry, still a Unity beginner)

**Comment by mrmwiebe** [comment]
there's a big invisible collider in the background that stops rays from passing through the camera, probably just needs to be enlarged.
