### ISSUE TITLE
Game names are cut off if longer than two line breaks

### ISSUE THREAD

**Issue by Ludonaut** [winnitron/WinnitronLauncher#21]
Another non-critical cosmetic issue, screenshots should be pretty self-explanatory:

![gamenamelength](https://cloud.githubusercontent.com/assets/932664/22312341/ae9d92f8-e357-11e6-895a-a958ec0bd444.png)
![gamenamelength2](https://cloud.githubusercontent.com/assets/932664/22312351/b3c52ade-e357-11e6-8b6d-f948d6963f24.png)
![gamenamelength3](https://cloud.githubusercontent.com/assets/932664/22312358/b9ed0882-e357-11e6-8676-dd48d39ebe8f.png)
(The full name was _"Canabalt Super Long Test Title Please Forgive Me Adam"_)

Maybe game names should be right-aligned (to the cover images) and, if they're too long for a single line (or before they're hitting the left edge of the screen), instead of breaking the line they could scroll through a small window from left to right, while they are selected.

**Comment by mrmwiebe** [comment]
Sorry for the long wait.  I was holding off on this because the launcher code was a jumble and it was daunting trying to wade through all the code.

This is going to be fixed for version 2.3 which will be a major UI and code refactoring update. :)
