### ISSUE TITLE
Menu to filter games by min/max number of players or tags

### ISSUE THREAD

**Issue by Ludonaut** [winnitron/WinnitronLauncher#22]
I bet you guys are already working on this but I figure it can't hurt to open an issue about it.

I'm thinking at some point when a machine has more than 20 games or so installed it would be cool to be able to filter them by tags or min/max number of players somehow.

Maybe a menu, selectable like a playlist, but to the left of all playlists, and only if more than one directional button is held, so it's not opened accidentally. This would also keep the horizontal loop of playlists intact.

**Comment by aaronklaassen** [comment]
Yeah this will show up on the website first (once there are more games there such that filtering is more required/useful), but I like the idea of options launcher-side too.

**Comment by mrmwiebe** [comment]
This can be done with the folders/playlists, at least at first.  Like if you wanted to have a 2-player list you can just make a new playlist for it.  Need to just get the sync and basic launcher stuff working smooth before adding this kind of stuff to it.  But yeah, if there's a simple way of filtering without cluttering the screen too much I'm open to it

**Comment by Ludonaut** [comment]
You're totally right, keeping multiple playlists is way simpler for now (though only one-dimensional, if that makes sense). :+1:

**Comment by aaronklaassen** [comment]
I think this is best left as custom playlists; I don't want to complicate the user interaction Launcher side, since watching people interact with the machines in real life reveals a lot of random button mashing :joy:
