### ISSUE TITLE
Hectic legacy games trigger AHK #MaxHotkeysPerInterval error dialog

### ISSUE THREAD

**Issue by Ludonaut** [winnitron/WinnitronLauncher#23]
We were playing a fierce battle of Nidhogg when we were thrown out of the game and this appeared:

![winnitronlegacymaxhotkeys](https://cloud.githubusercontent.com/assets/932664/22313565/8b87eee8-e35d-11e6-8164-cbfb581c510f.jpg)
(sorry for the horrible quality picture)

Google-Fu brought me to this page in the AutoHotKey docs:
https://www.autohotkey.com/docs/commands/_MaxHotkeysPerInterval.htm
>The maximum number of hotkeys that can be pressed in the interval specified by #HotkeyInterval without triggering a warning dialog.

I've tried adding that setting to WinnitronLegacy.ahk but to no avail.

We were able to just hit Yes and alt-tab back to the game without issue though. (I'd like to unplug the keyboard at some point for security reasons)

If you can't reproduce this I suspect it might also be triggered by a loose connection in the control panel or some misconfiguration in IPAC.

**Comment by mrmwiebe** [comment]
This is great that you're able to stress test this stuff! :D  I think that happened to me when I was first starting to use AutoHotkey and I forget why that was happening.  WinnitronLegacy is a standalone version of AHK with settings embedded, it might just be that we need to re-embed it with a higher interval setting.

**Comment by aaronklaassen** [comment]
Nice. Yeah this is highly relevant to the customizable-keymap stuff I've been sketching out.

**Comment by mrmwiebe** [comment]
@aaronklaassen do you want to look into this or should I?

**Comment by aaronklaassen** [comment]
@mrmwiebe Nah you go for it.

**Comment by mrmwiebe** [comment]
Ok a fixed version of the script will be included in the next release.  Autohotkey runs two ways.  It will run a script if the exe is named the same as the .ahk file, and you can make a standalone .exe that has the .ahk embedded in it.  Turns out I was trying to use both!
