### ISSUE TITLE
Halifax is still mentioned in the attract 😂

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/WinnitronLauncher#24]
It still says "Games from Halifax and around the world!" or something. Which isn't *wrong*, per se, but you know.

**Comment by mrmwiebe** [comment]
Gotcha.  I'll change it for the next version so the main install is a generic Winnitron attract

**Comment by mrmwiebe** [comment]
Fixed in commit 25a257438a737a1824afdbc40bedc70a0bc215e1 for Beta2
