### ISSUE TITLE
Version display

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/WinnitronLauncher#25]
We need an easy way for people to check what version - exactly - of the launcher they're running. So when we get bug reports we can say "oh shit yeah that was fixed in v2.1.14" or whatever.

**Comment by mrmwiebe** [comment]
I can just make it output to debug_log.txt first thing and make sure people are sending us that file or checking it.  That way it's not super obvious in the launcher itself.

**Comment by aaronklaassen** [comment]
Works for me. Just need it available somehow.

**Comment by mrmwiebe** [comment]
Fixed for RC1
