### ISSUE TITLE
Launcher doesn't reset/recover from legacy controls

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/WinnitronLauncher#27]
Launcher should reset to default controls:
* when a non-legacy game starts
* when any game exits
* when the launcher starts
* when the launcher exits
* hell even when the sync runs

Like, just spam the shit out of "reset to default keybindings". If a game crashes or even just exits or something when in legacy mode, the launcher menus etc don't even work because we can't hit any meaningful buttons.

The more problems we can solve with just "restart the launcher" or "force a re-sync" the better.

**Comment by mrmwiebe** [comment]
sounds like this bug hit a nerve ;)  I'll look into it.  Does this happen sporadically or everytime you quit a game?

**Comment by mrmwiebe** [comment]
uh, heh looks like I had commented out the bit that stopped the controls from shutting off :O
