### ISSUE TITLE
Hold "Home" to force quit

### ISSUE THREAD

**Issue by mrmwiebe** [winnitron/WinnitronLauncher#31]
This would be nice.

**Comment by mrmwiebe** [comment]
Don't think this is possible in Unity alone.  Would probably need some sort of watcher helper app or maybe it can be done with AutoHotKey?  This might be an undertaking....

**Comment by aaronklaassen** [comment]
Could be, yeah. Worth looking into, though.

**Comment by mrmwiebe** [comment]
I _think_ that this can be done with AutoHotKey.  I've asked in the forums.

**Comment by Ludonaut** [comment]
On Linux you can run programs as child processes and set up watchdog scripts.

It seems there is an equivalent in Windows. Google brought me here: https://msdn.microsoft.com/en-us/library/windows/desktop/ms686722(v=vs.85).aspx but I have no idea how this would work with Unity.

**Comment by mrmwiebe** [comment]
One day we'll use switch to Linux. ;)

Unity already can do this force closing stuff, it's more a matter of watching keyboard input in the background while still giving focus to the game.

**Comment by mrmwiebe** [comment]
OH YEAH.  The launcher will now kill a game by idling OR by holding down the home button for 3 seconds.
