### ISSUE TITLE
Launch game with any button press

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/WinnitronLauncher#35]
Launcher is currently picky about which button you press to start a game. I think anything that isn't a joystick should be **GO TIME** (especially home/esc: it feels like a start button).

**Comment by mrmwiebe** [comment]
Yeah that makes sense, will add in home to launch.  Though I'm going to keep it so that only Player 1 can launch/select games.  That way you know that someone's always at P1 controls.  P2 controls are for jukebox.
