### ISSUE TITLE
Launcher gets stuck on manual sync (ENTER/Return key)

### ISSUE THREAD

**Issue by Ludonaut** [winnitron/WinnitronLauncher#38]
On a machine without a keyboard, users shouldn't be able to do this because Return/Enter probably isn't mapped to any sticks or buttons, but:

If Return is pressed, the launcher gets stuck at "Collecting data for launcher..."
![stuckatmanualsync](https://cloud.githubusercontent.com/assets/932664/22670441/76539e76-ecc9-11e6-9874-9d3b55506a79.png)

The same thing happens in syncMode local, too, except there it says "SYNC DESCRIPTION":
![stuckatmanualsync2](https://cloud.githubusercontent.com/assets/932664/22670675/93266e10-ecca-11e6-9c38-723fb194f8ea.png)

As far as I can tell it is impossible to recover from this state except by ALT-F4 / killing and restarting the launcher.

(syncMode: normal)
[output_log.txt](https://github.com/winnitron/WinnitronLauncher/files/756094/output_log.txt)

(syncMode: local)
[output_log.txt](https://github.com/winnitron/WinnitronLauncher/files/756106/output_log.txt)

**Comment by aaronklaassen** [comment]
Yeah I meant to file this too. I'm not sure if it's stuck there or the sync is failing when manually triggered or what.
