### ISSUE TITLE
Launcher won't reactivate itself after a game quit until idle timeout

### ISSUE THREAD

**Issue by Ludonaut** [winnitron/WinnitronLauncher#39]
When quitting a game, the launcher won't respond until after the idle timeout has passed (10 seconds by default). It seems like the launcher doesn't register anymore if a game has quit itself.

![notresponding](https://cloud.githubusercontent.com/assets/932664/22803784/a7b72c5e-ef16-11e6-9db0-ff345fcd88db.png)

This happens with both legacy and non-legacy games, and sometimes it is possible to shorten the ten seconds by holding Back/Quit (the three second force-kill). Not really critical due to the incredible usefulness of the new idle timeout, but definitely a bug. 

Can't find anything interesting in the log, but for completion's sake:
[output_log.txt](https://github.com/winnitron/WinnitronLauncher/files/764997/output_log.txt)

**Comment by mrmwiebe** [comment]
Ohhhh, I think I know what's going on here.  Yep the new AHK script isn't checking to see if the process has quit on its own.

**Comment by mrmwiebe** [comment]
This is related to #42 and should be fixed when the AHK community gets back to me.

**Comment by mrmwiebe** [comment]
This should be fixed with commit 278a153
