### ISSUE TITLE
Hide mouse cursor by default

### ISSUE THREAD

**Issue by Ludonaut** [winnitron/WinnitronLauncher#40]
On our cabinet #39 also sometimes causes the mouse cursor to appear in the middle of the screen, which I can't reproduce on my laptop. Maybe since it doesn't support any pointer controls anyway the launcher should just hide the cursor by default?

**Comment by mrmwiebe** [comment]
I'll add in that whenever the launcher restarts it makes extra sure that it hides the cursor again.

**Comment by mrmwiebe** [comment]
Oh, I added a bit to the AHK scripts that force the mouse to move to the bottom-right corner everytime a game is launched so it shouldn't be an issue anymore.
