### ISSUE TITLE
Launcher fullscreen window off-center

### ISSUE THREAD

**Issue by Ludonaut** [winnitron/WinnitronLauncher#41]
While testing #39 on my laptop I ran into some weird window repositioning.

The launcher window was oddly not at full screen resolution during its Not Responding state:
![notrespondingwindow](https://cloud.githubusercontent.com/assets/932664/22805494/1bbbdaf8-ef1e-11e6-8535-5fc866f3f2ac.png)

Ten seconds later:
![launcheroffcenter](https://cloud.githubusercontent.com/assets/932664/22805497/20c91d58-ef1e-11e6-8193-e967e51fcc32.png)

This might be due to some weird external screen interaction (it's a 16:10 screen, hence the black bars) or just Windows 7 messing something up, I don't know.

Maybe there's a way the launcher could be more aggressive about keeping/restoring full screen resolution while keeping its window position fixed?

**Comment by mrmwiebe** [comment]
Is this happening on your actual arcade machine too?  Is your laptop and machine running different versions of windows?  There is a script that's supposed to be using Windows DLLs to align the window properly, but it's finicky. :/

**Comment by Ludonaut** [comment]
Our arcade machine is running on Windows 7 too, for now, though as far as I can tell this window thing has never happened there.

FWIW this only happens on my external monitor (even in 'Projector only' mode), so I think this might just be a weird Windows bug related to how it's handling external monitors? I guess we can close this issue until we're able to reproduce this bug on an actual Winnitron.

**Comment by mrmwiebe** [comment]
Oh yeah that is a good possibility.  I hadn't thought about taking more than one monitor into account.  If it does happen on your machine, let me know!
