### ISSUE TITLE
Idle timeout leaves Nidhogg running in backgound

### ISSUE THREAD

**Issue by Ludonaut** [winnitron/WinnitronLauncher#42]
Observed with: Nidhogg

How to reproduce:

- Start Nidhogg
- Don't touch anything for 10 Seconds aka wait until the launcher kills it
- Launcher comes back, does its thing
- You can hear Nidhogg still running while being able to select other games
- Alt-Tab confirms Nidhogg is still running

Starting the game again brings up another instance of the game. This leaves multiple garbage instances open and could probably crash machines or fill up RAM or something, if repeated often enough.

I've tested this with other games (Canabalt, Sumo Topplers), but couldn't reproduce it yet.

**Comment by aaronklaassen** [comment]
Ah this must be what I was talking about with you @mrmwiebe the other day. I didn't realize it was just Nidhogg though.

**Comment by mrmwiebe** [comment]
[I've asked the AHK community about it](https://autohotkey.com/boards/viewtopic.php?f=18&t=27533), will get on this when I get a reply.

**Comment by mrmwiebe** [comment]
I basically made AHK cycle through a bunch of possibilities.  Turns out it was trying to close "Nidhogg.exe" when the app was named "Nidhogg".
