### ISSUE TITLE
Flash-based legacy games switch to windowed mode on ESC instead of quitting

### ISSUE THREAD

**Issue by Ludonaut** [winnitron/WinnitronLauncher#44]
Both Canabalt and X-Bones can't quit-on-ESC anymore, but can still be killed by idle timeouts and hold-quit-for-three-seconds force-kills.

Definitely not breaking anything, just weird and ugly to people who don't know about force kills. :thinking:

**Comment by aaronklaassen** [comment]
Yeah I'm not sure we have a real solution for this - it's just old Flash being a old pain in the ass. That's why they're on a separate playlist.

If there's some way to fix it I'd really like to - both Canabalt and X-bones are great arcade games.

**Comment by mrmwiebe** [comment]
Could be done with a custom AHK script.  Really gotta get some sort of thing into the metadata that says what script to use...hmmm

**Comment by aaronklaassen** [comment]
@mrmwiebe Oh okay. Yeah. I was going to hold off on custom AHK until v2.1 (ie an implementation that would allow arbitrary keybindings), but if we could get a minimal version running to fix this bug we could expand it later.

**Comment by mrmwiebe** [comment]
@aaronklaassen could we add a metadata field that's something like "customAHK" with a string for now?  Then i can just have a "flash" template that the launcher runs.

**Comment by aaronklaassen** [comment]
@mrmwiebe How about

```javascript
{
  "title": "A Great Game",
  "foo": "bar",
  // other stuff
  "ahk": "flash", // other stuff could be "default", "custom", etc
  
  // and then in the future:
  "custom_ahk": "however we decide to format this"
}

**Comment by mrmwiebe** [comment]
So the functionality is there, just need it to be implemented on the Network side so that the proper JSON is in place.  278a153

**Comment by aaronklaassen** [comment]
@mrmwiebe Yep the API side is already done: https://github.com/winnitron/winnitron_reborn/pull/77
