### ISSUE TITLE
PICO8 Support!

### ISSUE THREAD

**Issue by mrmwiebe** [winnitron/WinnitronLauncher#45]
Okay, this is something i've been thinking about for a while because there's tons of great PICO8 games that are very arcadey.  I would love to be able to launch individual PICO8 games fullscreen, but it's a bit tricky because right now exported PICO8 games export as .html files and you cannot tell HTML5 apps to go fullscreen without user interaction as it's a security thing.

So, I'm thinking it can be done in one of two ways:
- Custom nwjs app that loads the PICO8 .html file and just displays it at max height.  nwjs has a "kiosk" mode that auto launches into "fullscreen" mode which is basically just resizing the website to full width and height, not the proper Fullscreen like when you click on the fullscreen button on a PICO8 game.
- Custom AHK script that "clicks" the fullscreen button for you when the game is launched thus satisfying HTML5's need to have user interaction.  Haven't tested this theory yet.

Anyways, just putting this here for now but if there's anyone with any other ideas lemme know!

**Comment by Ludonaut** [comment]
Ha! I **love** this!

One of our professors actually approached me about _this exact feature_ at the party last week. :tada: 

If it helps, a quick search on the bbs turned up [this guide on how to generate desktop builds of pico-8 games (via Electron)](http://missingsentinelsoftware.com/blog/deploying-pico-8-cartridges-electron).

I think it's a great idea, and if set up to just load plain pico-8 .html files like you suggested could save devs a lot of work and us 'tron builders a _ton_ of build size and traffic (way less duplication, not every small pico-8 game needs to ship their own nw.js/Electron).

Re: The fullscreen thing: I'm not 100% sure but I think nw.js/Electron don't have the "no fullscreen without user interaction" restriction, so there's probably no need to use their kiosk modes.

**Comment by aaronklaassen** [comment]
@mrmwiebe @Ludonaut Ha awesome. My first thought was "I bet we could build an app using electron or something..."

**Comment by mrmwiebe** [comment]
Well, i have something very bare bones running with NWJS, but looking into Electron.  I'm guessing/hoping they are very similar.

**Comment by aaronklaassen** [comment]
@mrmwiebe I was just speculating. You're already way farther along that me.

**Comment by Ludonaut** [comment]
Worth investigating: Maybe it's easier to just launch cartridges through pico-8 itself, like [this notepad++ setup](http://www.lexaloffle.com/bbs/?tid=4082) does.

Though that would require either working install of pico-8 on the arcade machine or bundling pico-8 with the launcher (licensing issues probably).

**Comment by mrmwiebe** [comment]
I'm 95% sure I can get it to work with a NWJS/Electron app, and possibly even without native fullscreen, it just kiosk modes and then uses CSS and a custom HTML file to make it fullscreen.  I'm hoping this means just having one executable and distributing it with the launcher which runs all the PICO-8 games without the builders having to purchase PICO-8.  Fingers crossed!

**Comment by mrmwiebe** [comment]
HELL YEAH.  PICO8 Support incoming. :D
