### ISSUE TITLE
Change AHK settings to read from API response

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/WinnitronLauncher#46]
This is deployed: https://github.com/winnitron/winnitron_reborn/pull/77 It adds `keys: { template: "something" } }` to the game API response.

- [x] SYNC: take that data and write it as-is (including the nesting) to `winnitron_metadata.json`
- [x] SYNC: *don't* write the `legacy_controls` key
- [x] AHK: check the metadata json for which key map script to use.
- [x] OPTIONS: remove all references to `legacy_controls`
  - this is no longer needed - it's the equivalent of `template == "legacy"`

Valid values for the `template` key are (this list is easy to add to):
- `default`
- `custom`
- `legacy`
- `flash` (#44)
- `pico8`

No games are `custom` yet because we haven't, you know, built that.

**Comment by mrmwiebe** [comment]
Cool.  Gonna do some rewriting of the way it handles templates first and then I'll get to this.

**Comment by mrmwiebe** [comment]
should be g2g with the latest commit 278a153
