### ISSUE TITLE
Exiting any game causes the launcher to switch to borderless window mode

### ISSUE THREAD

**Issue by hyperscope** [winnitron/WinnitronLauncher#52]
This includes manually quitting, force quit, and idle quit.

**Comment by mrmwiebe** [comment]
This is the old Winnitron that's doing this?  What's the resolution of the screen and the operating system that you're using?

**Comment by hyperscope** [comment]
Old launcher yes, but I just bought a new graphics card for it, issues persisted. I will follow up and test further on my end when I get home.

**Comment by hyperscope** [comment]
I'm temporarily using a GTX 1050, screen resolution 1600x900, DVI port. Changing the resolution to 1024x768 seems to fix the issue.

**Comment by mrmwiebe** [comment]
Hmm, okay that's good to know.  If you use a 16:9 resolution does that work as well?  I'm wondering if the launcher can only handle 16:9 or 4:3 ratios.

**Comment by hyperscope** [comment]
While demoing at First Friday on the projector setup error persisted regardless of resolution.

**Comment by mrmwiebe** [comment]
Was the projector the primary display?  Was it in mirror mode or were you using it in multiple display mode?  I think @ludonaut found this bug happened when he had a multi monitor setup.

**Comment by hyperscope** [comment]
It was the primary/only display.

**Comment by mrmwiebe** [comment]
This is a strange one as I can't test it on my machine as it works as intended and Aaron hasn't reported anything similar on his machine.  What version of Win are you using?

**Comment by hyperscope** [comment]
Windows 7 Ultimate 64-bit (6.1, Build 7601)

**Comment by mrmwiebe** [comment]
Ok great, yeah I wonder if this is a Win7 thing as I think the other Trons are using 10.  Maybe the DLL i'm calling to reset the screen works differently in Win7 and I should be calling something more version dependent, I'll look into it!

**Comment by hyperscope** [comment]
I will post my further testing in a spreadsheet but so far with 4Forths
Idle Quit: Proper fullscreen, game running in the background
Force Quit:  Proper fullscreen, NO game running in the background

**Comment by mrmwiebe** [comment]
Games running in background is more related to #53, I think @aaronklaassen made some changes to that side of things which should eliminate those issues for all games.  No need for a spreadsheet for that as Idle Quitting is not working properly for all games.

Also, is the fullscreen thing only happening on certain games?  I thought it was happening with all games on your machine?

**Comment by hyperscope** [comment]
Ah Okay. 

All games yes with the exception of 4Forths so far apparently, just tested it today and discovered it.

**Comment by hyperscope** [comment]
These games all exit back to proper fullscreen 
4Forths
N Arcade
Sumo Toppler

**Comment by mrmwiebe** [comment]
I'll see what I can do.  I suspect it has something to do with changing resolution when exiting the game.

**Comment by mrmwiebe** [comment]
The new version will have a batch file that you will need to run in order to make the launcher run in true borderless window mode and should not show the desktop when launching a game etc.
