### ISSUE TITLE
Unreal games left running in the background on quit

### ISSUE THREAD

**Issue by hyperscope** [winnitron/WinnitronLauncher#53]
Includes every method of quitting.

**Comment by mrmwiebe** [comment]
Can you send me a super basic Unreal game that I can use to test?  I bet it's just that AutoHotKey can't find the process by name or something.

**Comment by aaronklaassen** [comment]
@mrmwiebe Propaganda Llama.

**Comment by mrmwiebe** [comment]
I believe this should be fixed now with #60 being solved and #52
