### ISSUE TITLE
Make launcher able to run any .exe in local mode, not just one with same name as folder

### ISSUE THREAD

**Issue by hyperscope** [winnitron/WinnitronLauncher#55]
When trying to launch "Couch Coach" GM prompts for install every time, brings up dialog box installer, default install location set to C:\Users\winnitron\GGJ16 
Changed to C:\WINNITRON_UserData\Playlists\testing-playlist\couch-coach\GGJ16. Tried taking the contents of C:\WINNITRON_UserData\Playlists\testing-playlist\couch-coach\GGJ16 putting it into C:\WINNITRON_UserData\Playlists\testing-playlist\couch-coach, deleting the installer along with the now empty GGJ16 folder. No longer prompts for install but now I get the "Error: Failed attempt to launch program or document..."

I presume it has something to do with GM file install structure?

**Comment by mrmwiebe** [comment]
This is from the synced version of Couch Coach?  Sounds like maybe whoever uploaded it uploaded the installer and not the executable?

**Comment by hyperscope** [comment]
Correct and correct. Although I presumed going in after a sync and manually installing would have solved the issue.

**Comment by mrmwiebe** [comment]
Hmm, yeah the launcher should still be able to launch that.  What's the game's .exe name and is it in the root of the couch-coach folder?

Also, if you can run the launcher, get it to make that error again and send me the output_log.txt that would be helpful.

**Comment by hyperscope** [comment]
Oh geez my apologies I totally overlooked that the exe, name was getting renamed on install. Changing to the proper .exe name and it launched no problem.

**Comment by mrmwiebe** [comment]
Ok cool.  This is actually a good reminder that I need to change it so that it's looking for the only .exe in the folder not just one named the same as the folder.

**Comment by aaronklaassen** [comment]
The Launcher *does* run any exe - it gets that data from what the user enters on the website when they submit the game. Couch Coach just had bad metadata (it was uploaded before I reworked the game submission workflow). I'll double check, but I think this is `notabug`

**Comment by mrmwiebe** [comment]
Sorry!  Should clarify: this was for when the launcher is in local mode.  Just so if you have a game in a folder with a name that's not the same as the folder, it can still find the .exe and launch it.  Everything is working properly otherwise.

This also relates to issue #36

**Comment by aaronklaassen** [comment]
ohhhhhhhhhhhhhhhh

**Comment by hyperscope** [comment]
Specs: Windows 7/8.1 64bit
Issue: Launcher will freeze indefinitely when launching any game and the .exe is incorrectly named.
Resolution: Manually rename .exe
Comment: I don't think I included this in my initial report, specifically the launcher freezing part. Apologies if you guy's are already aware of it!

**Comment by mrmwiebe** [comment]
Ah, yeah haven't fixed this yet!  Will get to it for the next bugfix update.
