### ISSUE TITLE
Launcher menu loading lag

### ISSUE THREAD

**Issue by hyperscope** [winnitron/WinnitronLauncher#62]
**Specs**: Windows 8.1 64bit (Laptop-Tron) / Winnitron v2.0
**Issue**: On each new OS boot, after the title screen launcher will lag going into the menu on a white screen for 15-20 seconds. Consistently repeatable.
**Resolution**: Relaunching Winnitron launcher removes extended lag period.

**Comments**: Non issue on Windows 7 Ultimate 64bit (Winnitron Redux)

**Comment by mrmwiebe** [comment]
So, the lag gets longer as you play more games?  Or is this just after a fresh Windows reboot?

**Comment by mrmwiebe** [comment]
Could you send me a video of that and then maybe the output_log.txt file after it happens?

**Comment by hyperscope** [comment]
Lag becomes extended on a fresh Windows reboot. And gets shorter on each relaunch of the .bat
Video: https://youtu.be/6VVVdKnLb5w
[output_log.txt](https://github.com/winnitron/WinnitronLauncher/files/984320/output_log.txt)

**Comment by mrmwiebe** [comment]
Ok, hmm.  Does this happen after launching a game and coming back to the menu as well?

**Comment by hyperscope** [comment]
https://www.youtube.com/watch?v=6uLYzBHpixQ
Yes, but it gets progressively less so with each cycle through the launcher. Also now I'd say the initial lag at the worst is between 8-10 across all of my tests, although I haven't done anything differently to cause that.

**Comment by mrmwiebe** [comment]
I'm going to close this.  The launcher has been overhauled since this bug.  If it crops up again we can just make a new issue.
