### ISSUE TITLE
Idle quit variables not functioning

### ISSUE THREAD

**Issue by hyperscope** [winnitron/WinnitronLauncher#63]
**Specs**: Windows 8.1 64bit (Laptop-Tron) / Winnitron v2.0
**Issue**: idleTimeBeforeAttract, initialIdleTimeSeconds, and idleTimeSeconds all set to "99" but upon game launch and user is idle, time is 42 before being booted back to menu.
**Resolution**: Unknown
**Comments**: Also winnitrons_options.json resides in C:\WINNITRON\WINNITRON_Data\Options AND C:\WINNITRON_UserData\Options although it doesn't seem to use the former.

[winnitron_options_TEXT.txt](https://github.com/winnitron/WinnitronLauncher/files/984374/winnitron_options_TEXT.txt)

**Comment by aaronklaassen** [comment]
@hyperscope I ran into this too, but they are working - the format of the options json changed in `v2.0`: https://github.com/winnitron/WinnitronLauncher/blob/master/Assets/Options/Defaults/winnitron_options.json

Change your `runningGames` to `runner`.

The `C:\WINNITRON\WINNITRON_Data\Options` json file is just the default settings. You can ignore it.

**Comment by hyperscope** [comment]
Only 7mins, not bad response time :P

**Comment by hyperscope** [comment]
Forgive my ignorance but would it not be important to reference this in some fashion? As anyone that has an older version of the launcher won't have the updated formatting or even be aware of it.
