### ISSUE TITLE
Negative scale error

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/WinnitronLauncher#68]
Getting this in the logs:

> BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Prettiness/Planes/TesselatedPlane"

I haven't been able to replicate it locally so I don't have any more details yet.

**Comment by mrmwiebe** [comment]
Huh.  Interesting, well there isn't a need to have BoxColliders on the tesselatedPlanes anyways so I can probably just remove them.

**Comment by mrmwiebe** [comment]
Turns out the BoxColliders on the tesselated planes were scaled to a negative number from the get go.  OOPS
