### ISSUE TITLE
Skip sync if no network connection

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/WinnitronLauncher#83]
Sometimes the launcher boots up and can't connect to the internet, so just displays an error because the sync failed. This might be just "the wifi router is down" or something, though. So instead going full Oops Screen, log the error and continue to menu (ie skip sync).

Still should Oops though if the problem is a bad API key or something. i.e., more detailed error case/messages:

- can't connect at all
- Network returns status code other than `200 OK` (i.e., bad API key or something)

**Comment by Ludonaut** [comment]
I've had this happen on our machine while trying to autorun the launcher right after booting.

**Comment by aaronklaassen** [comment]
@Ludonaut Yeah that's what brought this up for me too - a friend saw my Half-a-tron in a bar stuck at "error fetching playlist" 😅
