### ISSUE TITLE
Broken Oops state if sync fails

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/WinnitronLauncher#84]
error reporting broken lol

> `NullReferenceException: Object reference not set to an instance of an object
OopsState.OnStateEnter (UnityEngine.Animator animator, AnimatorStateInfo info, Int32 layerIndex) (at Assets/Scripts/System/StateMachine/States/OopsState.cs:17)`

> `NullReferenceException: Object reference not set to an instance of an object
OopsState.OnStateUpdate (UnityEngine.Animator animator, AnimatorStateInfo info, Int32 layerIndex) (at Assets/Scripts/System/StateMachine/States/OopsState.cs:32)`

I'm not sure yet if this happens with *all* Oopses or just this early one. You can replicate it by forcing an error connecting to the Network (e.g., enter a garbage URL in the `sync.libraryURL` option). The GET fails, tries to Oops, and throws the above exceptions.

**Comment by mrmwiebe** [comment]
SON OF A

**Comment by mrmwiebe** [comment]
Haha, well I guess that one is extra fixed now.

**Comment by mrmwiebe** [comment]
Oops, well I pushed it to the wrong branch anyway.  I know how to Git

**Comment by aaronklaassen** [comment]
@mrmwiebe Hah sorry - I filed the issue, walked away, came back and went "ohhhhhhhhhhh".
