### ISSUE TITLE
Recommended specs?

### ISSUE THREAD

**Issue by ngscheurich** [winnitron/WinnitronLauncher#89]
Hi all,

Is there a codified set of minimum/recommended system specs for a Winnitron machine?

**Comment by mrmwiebe** [comment]
Hi there!  At this time there isn't.  It seems to work pretty well on any modern PC.  To be honest, I'm not even sure how one would go about figuring this out unless we start getting people installing it on various PCs with different specs and reporting their experience back.

Do you have a machine that you are thinking of installing it on, or thinking of building a new machine with the minimum specs?

**Comment by ngscheurich** [comment]
Hey, @mrmwiebe! I'm in the process of planning out a new build and was just looking for some guidelines to help with working out a budget. Sounds like I'll be safe choosing some low-to-mid range parts so I'll start there and see how things go. I'll post back here or on the subreddit when the build is complete! 🤘🕹

**Comment by aaronklaassen** [comment]
The primary issue is that while the specs for the Launcher are pretty minimal, specs for individual *games* can vary widely. Some of them are heavy Unreal Engine, and some are PICO8, you know?

**Comment by aaronklaassen** [comment]
Yeah. The [Half-a-tron 500](https://medium.com/@aaronklaassen/building-the-half-a-tron-500-5d18d045337c) is *definitely* low-end hardware. 😅
